services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ../DEnTS:/app/DEnTS 
      - local_media_storage:/app/media
    env_file:
      - ./.env

volumes:
  local_media_storage: