# Generated by Django 5.0 on 2026-03-31 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0009_remove_codigo_data_codigo'),
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('tempo_total_ms', models.IntegerField(blank=True, null=True)),
                ('quantidade_jogadores', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoTorneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField()),
                ('fichas_finais', models.FloatField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codigos.codigo')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='mesas.torneio')),
            ],
            options={
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa_id_original', models.IntegerField()),
                ('log_arquivo', models.CharField(max_length=255)),
                ('tempo_processamento_ms', models.IntegerField()),
                ('fase', models.IntegerField(default=1)),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='mesas.torneio')),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='torneio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mesas.torneio'),
        ),
    ]
