# Generated by Django 5.0 on 2026-04-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_torneio_resultadotorneio_historicopartida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicopartida',
            name='detalhes_erro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicopartida',
            name='status_execucao',
            field=models.CharField(default='sucesso', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicopartida',
            name='log_arquivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicopartida',
            name='tempo_processamento_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
