# Generated by Django 5.0 on 2024-03-26 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigo',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
