# Generated by Django 5.0 on 2024-03-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0002_rename_usuario_codigo_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigo',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
