# Generated by Django 5.0 on 2024-04-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0008_alter_codigo_data_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigo',
            name='data_codigo',
        ),
    ]
