# Generated by Django 5.0 on 2024-05-20 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codigos", "0008_alter_codigo_data_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codigo",
            name="data_codigo",
            field=models.DateField(default=datetime.date(2024, 5, 20)),
        ),
    ]
