# Generated by Django 5.0 on 2024-06-01 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("codigos", "0009_remove_codigo_data_codigo"),
        ("codigos", "0010_alter_codigo_data_codigo"),
    ]

    operations = []
